security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

        in_memory:
            memory:
                users:
                    hafedh51: { password: 09200548, roles: [ 'ROLE_ADMIN' ] }

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:          ROLE_USER
        ROLE_APPLICANT:     ROLE_APPLICANT
        ROLE_RECRUITER:     ROLE_RECRUITER
        ROLE_ADMIN:         [ROLE_ADMIN, ROLE_APPLICANT, ROLE_RECRUITER]

    firewalls:
        main:
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 jours en secondes
                path:     /
                domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER

            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }