Superjobs\HomeBundle\Entity\CVtheque:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        lastename:
            type: string
            length: 255
        email:
            type: string
            length: 255
        cvFile:
            type: string
            length: 255
            column: cv_file
    lifecycleCallbacks: {  }
