Superjobs\HomeBundle\Entity\Jobs:
    type: entity
    table: Jobs
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_user
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        categories:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        type:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        company:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        logo:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        url:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        location:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        salary:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        skills:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        emailcv:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: emailCV
        token:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        isPublic:
            type: boolean
            nullable: true
            comment: ''
            column: is_public
        isCreated:
            type: boolean
            nullable: false
            comment: ''
            column: is_created
        expiresAt:
            type: datetime
            nullable: false
            comment: ''
            column: expires_at
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
    lifecycleCallbacks: {  }
