## YAML Template.
#---
# Acme/UserBundle/Resources/config/config.yml
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Superjobs\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
        
pugx_multi_user:
    users:
        Recuiter:
            entity: 
                class: Superjobs\UserBundle\Entity\Recuiter
#          factory: 
            registration:
                form: 
                    type: Superjobs\UserBundle\Form\Type\RegistrationRecuiterFormType
                    name: fos_user_registration_form
                    validation_groups:  [Registration, Default]
                template: SuperjobsUserBundle:Registration:Recuiter.form.html.twig
            profile:
                form:
                    type: Recuiter\UserBundle\Form\Type\ProfileRecuiterFormType
                    name: fos_user_profile_form
                    validation_groups:  [Profile, Default] 
        Applicant:
            entity: 
                class: Superjobs\UserBundle\Entity\Applicant
            registration:
                form: 
                    type: Superjobs\UserBundle\Form\Type\RegistrationApplicantFormType
                template: SuperjobsUserBundle:Registration:Applicant.form.html.twig
            profile:
                form: 
                    type: Superjobs\UserBundle\Form\Type\ProfileApplicantFormType