fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Irmasoft\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
        
pugx_multi_user:
    users:
        recruiter:
            entity:
                class: Irmasoft\UserBundle\Entity\Recruiter
            registration:
                form: 
                    type: Irmasoft\UserBundle\Form\Type\RegistrationRecruiterFormType
                    name: fos_user_registration_form
                    validation_groups: [Registration, Default]
                template: IrmasoftUserBundle:Registration:recruiter.form.html.twig
            profile:
                form:
                    type: Irmasoft\UserBundle\Form\Type\ProfileRecruiterFormType
                    name: recruiter_profile_form
                    validation_groups: [Profile, Default] 
        applicant:
            entity: 
                class: Irmasoft\UserBundle\Entity\Applicant
            registration:
                form: 
                    type: Irmasoft\UserBundle\Form\Type\RegistrationApplicantFormType
                template: IrmasoftUserBundle:Registration:applicant.form.html.twig
            profile:
                form: 
                    type: Irmasoft\UserBundle\Form\Type\ProfileApplicantFormType